### PR TITLE
Added attempted support for :upward

### PR DESCRIPTION
**Pull request by DandelionSprout**
Surely it has to be as easy as this... right?

As per https://github.com/uBlockOrigin/uAssets/issues/6397#issuecomment-640221808.

### CODE REVIEW

**Comment by llacb47** [comment]
Yes, but upward can also be used with selectors. 

for example: `mysite.com##.something:upward(article)`

**Comment by DandelionSprout** [comment]
That kind of functionality seems to be pretty rarely used, being used in 2 entries in *uBlock Filters*:

```
hentai2read.com##[src^="//"]:upward([target="_blank"])
prepostseo.com##.adsbygoogle:upward(.col-lg-12.text-center)
```

I am not an expert on Xpath, but I guess I need to look up some stuff on the uBlock wiki now.

**Comment by THEtomaso** [comment]
Even if uBO Legacy would be unable to convert such rules, at least its current convertion scheme won't conflict with them.

As for the examples that you posted, DS, it looks like **AdGuard Base filter** has a more legacy-friendly way of solving it:
```
hentai2read.com##.content > div[class] > div.afs_ads ~ div[class] a[target="_blank"] > img
prepostseo.com##.text-center > .text-uppercase.text-muted
```
:)

**Comment by krystian3w** [comment]
https://agrd.io/report

**Comment by DandelionSprout** [comment]
Okay, so after 20min, I've found a way to convert `:upward(.class)` and `upward(#id)`, but **not** `:upward([target="_blank"])` nor `:upward(element-type)`. My conversion method also wouldn't be possible to add to https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/src/js/assets.js unless it was possible to do RegEx conversion stuff in that file.

Essentially: `prepostseo.com##.adsbygoogle:upward(.col-lg-12.text-center)` → `prepostseo.com##.adsbygoogle:xpath(ancestor::*[@class='col-lg-12'][@class='text-center']/descendant::*[@class='adsbygoogle'])

This would require a RegEx conversion along the lines of `#(.*):upward\(\.(.*)\)` → `#\1:xpath(ancestor::*[@class='\2']/descendant::*[@class='\1'])`

**Comment by DandelionSprout** [comment]
@krystian3w I believe THEtomaso said he enjoyed a particular AdGuard Base solution, not that he had a problem with an AdGuard tool.

**Comment by THEtomaso** [comment]
> Essentially: `prepostseo.com##.adsbygoogle:upward(.col-lg-12.text-center) → prepostseo.com##.adsbygoogle:xpath(ancestor::*[@class='col-lg-12'][@class='text-center']/descendant::*[@class='adsbygoogle'])`
> 
> This would require a RegEx conversion along the lines of `#([a-zA-Z0-9].*):upward\(\.(.*)\) → #\1:xpath(ancestor::*[@class='\2']/descendant::*[@class='\1'])`

Holy *^'#, DS, that's next level stuff right there! :)

**Comment by DandelionSprout** [comment]
I feel that I'm goddamn good with RegEx if given a good opportunity. 😊

**Comment by krystian3w** [comment]
IMO better report via tool as manually create issue on github (bot add labels).

**Comment by THEtomaso** [comment]
Considering the extreme rarity of potentially remaining rules (which can't be converted), alternative fixes can always be added to the Legacy list.
That's what it's for! :)

**Comment by gwarser** [comment]
>`upward(.col-lg-12.text-center) → prepostseo.com##.adsbygoogle:xpath(ancestor::*[@class='col-lg-12'][@class='text-center']`

In CSS selector "dot" notation you can write `.a.b`, `.b.a`, `.a`, `.b` to select node with `class="a b c"`. 

You can also use attribute selectors `[class="a b c"]`, `[class^="a b"]`, `[class$="b c"]` or probably `[class~="b"]` (space separated words, I did not used it yet).

In xpath only attribute selector can be translated "easily" to `[@class="a b c"]`. CSS "dot" notation requires something like this: `[contains(concat(' ', @class, ' '), ' a ')]` (spaces are important).

**Comment by krystian3w** [comment]
the problem won't be the spaces between the quotes?

> `class=" a b c "`

**Comment by gwarser** [comment]
In html source it can be in any order - `class="a b c"`, `class="c b a"`. Xpath allows only to compare strings by `contains()`. If you compare by `[contains(@class, "a")]` it will also match `class="bar baz"`. `[contains(@class, "a ")]` will not match `class="c b a"`. You need to "expand" `@class` by adding spaces on both sides and then you can check if it contains word with spaces on both sides.

**Comment by THEtomaso** [comment]
@gorhill:
Could you please push a new legacy build, with this PR included?
Many rules are useless now, without it.

**Comment by DandelionSprout** [comment]
I was told on Slack today that it was allegedly better to ping @JustOff about this rather than Gorhill.

**Comment by THEtomaso** [comment]
> better to ping JustOff about this rather than Gorhill.

Normally, yes.
..but I don't think that he's available, at the moment:
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/232#issuecomment-636475918

**Comment by JustOff** [comment]
Sorry for not being very responsive lately. As I already [wrote](https://github.com/gorhill/uBlock-for-firefox-legacy/issues/232), there are several significant updates that need to be ported from the mainstream, but I have not done so yet. Last weekend, I finally found an opportunity to pay attention to this task and hope to complete it over the next weekend. These updates will also include support for the `upward` operator in filter syntax converter, just as you suggested here.

**Comment by JustOff** [comment]
Absorbed by https://github.com/gorhill/uBlock-for-firefox-legacy/commit/3d979a0bcab0ca93b1ece167e039e2a7ce518523.

**Comment by THEtomaso** [comment]
Big thanks for uBO Legacy v1.16.4.21, JustOff!! :)

Now, there are only two remaining `:upward` rules left in uBO filters, AFAICT.
Namely these:
```
hentai2read.com##[src^="//"]:upward([target="_blank"])
prepostseo.com##.adsbygoogle:upward(.col-lg-12.text-center)
```
Preferably, legacy-friendly alternatives should be added to the Legacy filter.
I gave that first one a try myself (with various `-abp-` attempts), but came up short. :(
As for the last one, I couldn't even figure out what it's actually targeting!
Anyone up for the task? :)

**Comment by gwarser** [comment]
hentai2read.com##[src^="//"]:xpath(//ancestor-or-self::*[@target="_blank"])
    prepostseo.com##.adsbygoogle:xpath(//ancestor-or-self::*[contains(concat(" ", @class, " "), " col-lg-12 ")][contains(concat(" ", @class, " "), " text-center ")])

?

**Comment by THEtomaso** [comment]
Great, gwarser!
That first rule seems to work just as well as the one found in uBO filters.
It's only a semi-working solution though, as the page needs to be refreshed once, before the rule takes hold (with an empty cache).
This is also the case with the `:upward` solution (found in uBO filters), when used in Chromium.

Again, as for that second rule..
Did you figure out what it's actually ment to target?

**Comment by llacb47** [comment]
The second rule hides placeholders.

**Comment by gwarser** [comment]
image

**Comment by gwarser** [comment]
> It's only a semi-working solution though, as the page needs to be refreshed once, before the rule takes hold (with an empty cache).

In Waterfox classic I see some flashing but it works.

**Comment by THEtomaso** [comment]
> The second rule hides placeholders.

Ah, that's it! :)
I can then confirm that both of your legacy-friendly rules work! :+1: 

On a side note, @ `prepostseo.com`, there are still a big Chrome extension ad, and an empty adbox with an "ADVERTISEMENT" label, in the sidebar!
I was able to successfully remove them with these rules:
```
prepostseo.com##span:has-text(ADVERTISEMENT)
prepostseo.com#?#[class^="col-md"]:-abp-has(h3:-abp-contains(Chrome Extension))
```

**Comment by THEtomaso** [comment]
@okiehsch:
Could you please add the rules that gwarser posted here to uBO's Legacy filter?:
https://github.com/gorhill/uBlock-for-firefox-legacy/pull/234#issuecomment-647037477

..and while at it, remove this listing too, if mapx- doesn't beat you to it:
https://github.com/uBlockOrigin/uAssets/commit/599d454e74059b1560b8636d5c0770548d99b618
:)

**Comment by okiehsch** [comment]
Done.

**Pull request closed without merging**
