### PR TITLE
Added a Legacy-specific version of my list

### PR DESCRIPTION
**Pull request by DandelionSprout**
Hopefully as simple as the title says.

If not, then I've turned on the "Allow edits by maintainers" button for this PR.

### CODE REVIEW

**Comment by JustOff** [comment]
I was told by Raymond several times that using the XUL name against uBO for Firefox Legacy is not correct, so could you please change the title to `NOR, DNK, ISL: Dandelion Sprouts nordiske filtre (Legacy)` and the file name to something like `NordicFiltersLegacy.txt`?

**Comment by DandelionSprout** [comment]
Sure thing. Give me 10min.

**Comment by DandelionSprout** [comment]
Okay, I seem to have fixed it now.

**Comment by AroKol78** [comment]
invalid filter - it is not 100% compatible
testnord

**Comment by DandelionSprout** [comment]
I'll look into how to fix them with RegEx. Give me 30min.

**Comment by JustOff** [comment]
Merged in https://github.com/gorhill/uBlock-for-firefox-legacy/commit/8024518ddd356570c137d35e618a09e9b99d5673

I also changed the title to `NOR, DNK, ISL: Dandelion Sprouts nordiske filtre – Legacy` just like "[uBlock filters - Legacy](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/8024518ddd356570c137d35e618a09e9b99d5673/assets/assets.json#L40)".

**Comment by AroKol78** [comment]
it is strange `Invalid network filter in NOR-0: gamereactor.*$$script[onError="adblockEnabled()"]`
`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFilters-NotFirefox.txt`

```
!#if adguard
gamereactor.*$$script[onError="adblockEnabled()"]
!#endif
!#if env_firefox
gamereactor.*##^script[onError="adblockEnabled()"]
!#endif
```

**Comment by DandelionSprout** [comment]
The most likely caused was that I was using `AntiAdblockFilters.txt` as an `!#include` file, despite already being included in the list generation script to begin with, resulting in a few dozen duplicate entries.

**Pull request closed without merging**
