### PR TITLE
Add no scripting feature

### LINKED ISSUE #95: Missing feature: No scripting
Reference:
https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting

### PR DESCRIPTION
**Pull request by hawkeye116477**
Fixes #95

### CODE REVIEW

**Comment by JustOff** [comment]
Given this adds three new entities to `src/_locales/en/messages.json`, please include here only related changes to the other locales, and split out the general update of upstream translations into a separate PR.

This will allow us to manage the sources more accurately in case something goes wrong with this particular PR.

**Comment by hawkeye116477** [comment]
Ok, seems I followed bad plan. Better would be probably for first fix json formatting and sort, then would be easier to split the rest.

**Comment by JustOff** [comment]
I would ask you, if possible, not to make the update of locales from upstream a pre-requisite to the rest of the PR and leave it for later. The main issue with translations is that I would not want to update them without a detailed study of the changes in the original strings and probably the help of the translators.

**Comment by hawkeye116477** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/pull/263/commits/10e48b4dfb5f0b7ba2cec77d56e9af784c901e99 contains only new added strings, the rest is „pretty print".

I'm not sure if I understand, do you want only English strings or just not update not related strings with changes?

**Comment by JustOff** [comment]
For your convenience, here is the locales update you need for this PR: https://github.com/JustOff/uBlock-for-firefox-legacy/commit/7be99dac540447fd6d5d729782de14b1dfa6ea7b.

**Comment by hawkeye116477** [comment]
Ok, I'll remember this, added.

**Comment by JustOff** [comment]
Sorry, I messed up with https://github.com/JustOff/uBlock-for-firefox-legacy/commit/7be99dac540447fd6d5d729782de14b1dfa6ea7b, now fixed.

**Comment by JustOff** [comment]
Here is the beta version to test: [uBlock0_1.16.4.26b9.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5359244/uBlock0_1.16.4.26b9.firefox-legacy.xpi.zip), I just put it in my main profile.

It also includes already verified and merged issues #264, #265, #266, #267, #268, #269 and #270. 

Ping @THEtomaso.

**Comment by hawkeye116477** [comment]
Shouldn't that be now 1.16.5 or maybe 1.17.0?

Anyway, this is not the end of what I want to share. After you merge that, I'll send 2 PRs, one with few general locales updates from upstream (few original English strings changed and the rest not related, which I noticed that got changed in my primary language) and the other with new dashboard.

**Comment by hawkeye116477** [comment]
@TheTomaso So everything is all right with this?

**Comment by THEtomaso** [comment]
I fiddled around with it a bit, after first installing v1.16.4.26b9..
At first, I wasn't sure if its enabled/disabled state interacted correctly with uBO's "My rules" window.
..but after comparing it with uBO's main branch, I'd say that it works like intended! 👍

**Comment by JustOff** [comment]
Sorry for not being very active here, I've been a bit short of time recently. I'll try to get the release ready by the end of the week.

**Pull request merged**
