### PR TITLE
Add support for Iceape-UXP

### PR DESCRIPTION
**Pull request by djames1**
Add support for IceApe-UXP (Seamonkey fork based on UXP)
https://wiki.hyperbola.info/doku.php?id=en:project:iceape-uxp

### CODE REVIEW

**Comment by JustOff** [comment]
Have you verified that uBO is working there properly?
Also, please specify the correct `minVersion`.

**Comment by djames1** [comment]
@JustOff Yes I am using it on IceApe properly. I will fix the version shortly.

**Comment by JustOff** [comment]
You can't use `*` in `minVersion`, see [Add-ons/Install_Manifests](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Install_Manifests).

**Comment by djames1** [comment]
@JustOff Fixed issues with minVersion

**Comment by JustOff** [comment]
Well, given the [questionable similar request](https://github.com/JustOff/ca-archive/pull/73#issuecomment-591534300), this PR requires additional testing and verification.

**Comment by djames1** [comment]
@JustOff What sort of additional testing and verification would you like to be done? I would be glad to assist in any way you need. I am using this addon on Iceape-UXP right now, just as I used it on SeaMonkey in the past.

2020-02-27-113048_2560x1440_scrot

**Comment by JustOff** [comment]
I did a cursory test, and everything seems to work as expected. Could you please update the application name spelling in the commit description and comments?

**Comment by djames1** [comment]
@JustOff Commit and comments updated.

**Pull request merged**
