### PR TITLE
Redesign dashboard

### PR DESCRIPTION
**Pull request by hawkeye116477**
Gorhill together with dashboard redesigned also popup, but because seems that will require more work, so I skipped work for popup for now.

In case of https://github.com/gorhill/uBlock-for-firefox-legacy/pull/274/commits/7e1ac994fbf03992b023ab7a30f316c287ae79c8, I'm not sure if this is needed, cuz I haven't seen now legacy Firefox forks for Android, so maybe class should be added directly instead of.

### CODE REVIEW

**Comment by JustOff** [comment]
It seems you forgot to add the Metropolis font itself.

PS: I wish I could disable all external fonts completely, they look so disgusting when anti-aliasing is turned off.

**Comment by hawkeye116477** [comment]
@JustOff Both things done.
You can set uiStyles to bypass uBO's default CSS styles.

**Comment by JustOff** [comment]
Oh, you're just an eye savior!

Here is the beta version to test: [uBlock0_1.16.4.27b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/5490363/uBlock0_1.16.4.27b1.firefox-legacy.xpi.zip)

Ping @THEtomaso.

**Comment by THEtomaso** [comment]
Sorry, but I've absolutely hated this design, since gorhill first released it for the main branch!
Especially that part about having to click on those tiny eye icons, in order to inspect filter assets!!
Is there a way to restore the classic interface?

**Comment by hawkeye116477** [comment]
You can override some things by myself in advanced settings, by setting appropriate value for `uiStyles`, for example `font-size: 20px;`.

**Comment by THEtomaso** [comment]
> `uiStyles`

Yeah, I've already tried messing around with that option, and it really doesn't fix anything.
The only place where size is a real issue, is in the blocking window, which I pointed out, and `uiStyles` doesn't affect it at all!
Just look at it.. it's ridiculous!

### New interface:
ubo-blockingwindow-new

### Old interface:
ubo-blockingwindow-old

**Comment by hawkeye116477** [comment]
`uiStyles doesn't affect it at all!`

It affects, font-size is set to body, but doesn't change font-size for elements wrapped in `code`, cuz gorhill decided that for class `code` will be slightly smaller size, so it can't be overridden that way.



Theoretically I could make switch for UI slightly similar to classic in advanced settings, if someone would like, but that decision belongs to boss. Just adding class `classic` to html and some css to it would be relevant, probably the only problem would be with these eyes.

**Comment by JustOff** [comment]
> Sorry, but I've absolutely hated this design, with slightly blurred text and superfluous coloring, since gorhill first released it for the main branch!
> Especially that part about having to click on those tiny eye icons, in order to inspect filter assets!!
> Is there a way to restore the classic interface?

To be honest, I am not happy either, but I understand that my personal preferences cannot be a reason not to follow the upstream in this matter.
 
> Also, why is everything in uBO's **document-blocked.html** window so damn small with this design?
> It's only half the size of what it used to be.
> Almost seems like a deliberate attempt to make things more difficult to read!

Have you, or someone else, tried to raise this issue?

> Theoretically I could make switch for UI slightly similar to classic in advanced settings, if someone would like, but that decision belongs to boss

I believe we are free to add advanced settings to adjust the font size on `document-blocked.html`, provided that the defaults match the upstream style.

**Comment by THEtomaso** [comment]
> Have you, or someone else, tried to raise this issue?

I searched the repo, but couldn't find any references to it, so I filed a new report here:
https://github.com/uBlockOrigin/uBlock-issues/issues/1326/

**Comment by AroKol78** [comment]
Browser UXP (my res 1440x900)
All much better colors
1.perfect look
ublockTest2
2.a bit small
ublockTest1
3.there is no big difference
ublockTest3

**Comment by JustOff** [comment]
> 3.there is no big difference

This hasn't been updated yet.

**Comment by THEtomaso** [comment]
> I filed a new report

Well, that was declined real fast.

--

> I believe we are free to add advanced settings to adjust the font size on `document-blocked.html`

Looks like that will be our best solution then.

**Comment by AroKol78** [comment]
I do not know if the font changed 3.
"%" - it looks different
ublockTest4

**Comment by hawkeye116477** [comment]
Yes, some changes are common to all uBO pages.

**Comment by AroKol78** [comment]
> > 3.there is no big difference
> 
> This hasn't been updated yet.

@JustOff 
> @AroKol78 Yes, some changes are common for all uBO pages.

**Comment by AroKol78** [comment]
on the occasion Redesign UI
ublockFix0
system uses polish,browser uses english (no languages)

**Comment by THEtomaso** [comment]
> on the occasion Redesign UI

Considering that the latest beta build contains a new UI, it might be prudent to perform a clean install.
This might help to avoid those type of issues:
1 - Uninstall uBO.
2 - Close Pale Moon.
3 - Delete this file:
`C:\Users\*****\AppData\Roaming\Moonchild Productions\Pale Moon\Profiles\eqs2jnu1.default\extension-data\ublock0.sqlite`
4 - Reinstall uBO.

**Comment by AroKol78** [comment]
so I did and deleted startupCache.4.little
good detection automatic selection of regions ( Regions, languages (2/34) )
and
ublockFix2

**Comment by JustOff** [comment]
@THEtomaso, I am very upset by the way you discussed [that issue](https://github.com/uBlockOrigin/uBlock-issues/issues/1326) with Raymond. Is it really so difficult to stop when the decision has already been made and reasoned, even if you disagree? Now I'm not sure if adding a font size adjustment option here would not be considered disrespectful to the project leader.

I'll try to clarify this question after a while, when all this calms down, but for now you have to get around using userContent.css, for example like this:

```css
@-moz-document url-prefix(chrome://ublock0/content/document-blocked.html) {
  body, button, select, .code {
    font-size: 18px !important;
    line-height: 27px !important;
  }
}
```

**Comment by THEtomaso** [comment]
> I am very upset by the way you discussed that issue with Raymond.

Agreed.
To be honest, I had a couple of beers, and the post didn't quite come out the way that I intended.
I threaded a bit wrong already in the first post.
It was a bit of copy/paste work from my post here in this thread, and once I realized what I had written, the damage was already done. :(
I really shouldn't have used the word "ridiculously", bacause it made the post sound hostile.
That's why I tried to soften the conversation in my second post, with a joke, which obviously failed too!
Anyway, I didn't try to intentionally make the empty space look bigger than it was, so I felt that I needed to point that out.
In hindsight, I should have chosen my words differently, but developers could also benefit from acting more polite in general, as you're probably well aware of, from other projects (without mentioning names).

--

> Now I'm not sure if adding a font size adjustment option here would not be considered disrespectful to the project leader.

I won't use that misplaced word again, but I think that sounds a bit far-fetched.
Such a tweak would be considered very minor, and I'm sure gorhill wouldn't have any objections to it!

**Comment by JustOff** [comment]
> ublockFix0
> system uses polish,browser uses english (no languages)

What is your browser and OS? Can you reproduce this with the latest Firefox and uBO?

**Comment by gwarser** [comment]
Missing font glyph for Fullwidth Plus Sign https://unicode-table.com/en/FF0B/

＋+＋+

**Comment by AroKol78** [comment]
> Can you reproduce this with the latest Firefox and uBO?

no technical possibility

> What is your browser and OS?

ubloc01

**Comment by JustOff** [comment]
Well, then it's a browser issue and you have to contact the author(s).

**Comment by THEtomaso** [comment]
> you have to get around using **userContent.css**

Actually, it's not that big of a deal for me personally, since I've got perfect eye sight.
I DID however find that blocking dialog unreasonably small, so there's no doubt in my mind that people with poor eye sight will have difficulties reading it, dependig on their system setups!

--

> I'll try to clarify this question after a while, when all this calms down

An argument can be made that a considerable amount of users will install blockers, without ever looking at their program settings.
Of course, uBO already comes with a rather forgiving default profile, to cater such users.
Nevertheless, many people that use software in such a manner, also happens to be amongst the group of people which actually HAVE poor eye sight!
Whilst they might get around just fine, whithout ever looking into uBO's settings, the **document-blocked.html** dialog is something that they more than likely WILL encounter at one time or another!
When this happens, it's imperative that they're able to read, and understand, what's happening!!

**Comment by AroKol78** [comment]
> system uses polish,browser uses english (no languages)

it's not a browser error, it's just switching **general.useragent.locale** en-US <> pl
ubloc02

**Comment by JustOff** [comment]
It is unlikely that one can help you until you provide detailed information about your system and the exact steps to reproduce the issue according to [this template](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/.github/ISSUE_TEMPLATE.md). My guess is that you are using Windows XP and your browser simply cannot display woff2 fonts there correctly. In this case, you will have to [use the system font](https://github.com/gorhill/uBlock-for-firefox-legacy/pull/274/commits/013b64a3e3733d72da09369ba0d63c684ac1a9df) or ask the browser dev(s) and/or the relevant community for help.

**Comment by AroKol78** [comment]
just switch **general.useragent.locale** to other than OS and take a look at immediately uBlock

**Comment by JustOff** [comment]
Can't reproduce. Please follow the instructions provided above.

**Comment by gwarser** [comment]
It's displayed correctly on Polish locale because I "translated" "Fullwidth Plus Sign" (`＋`) to simple "Plus Sign" (`+`) [on Crowdin](https://crowdin.com/translate/ublock/13/enca-pl?filter=basic&value=0#q=%EF%BC%8B).

**Pull request merged**
