### PR TITLE
Add a pane in the dashboard to assign keyboard shortcut

### LINKED ISSUE #250: Missing feature: UI for assigning keyboard shortcuts
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Keyconfig element is already created from the start, but there is no UI for binding keys.

As a reference you could take a look at [Dorando Keyconfig](http://forums.mozillazine.org/viewtopic.php?t=72994) or TGS.

### Your environment

* uBlock Origin version: 1.16.4.23
* Browser Name and version: Basilisk 2020.06.10
* Operating System and version: Manjaro 20.0.3 Lysia

### PR DESCRIPTION
**Pull request by hawkeye116477**
This fixes #250.

Additionally now it's also possible to use special keys like F1 for assigning shortcut (previously you could set keyboard shortcuts on about:config, but that special keys can't work).

It's based on gorhill's work.

### CODE REVIEW

**Comment by JustOff** [comment]
Thank you, it seems everything works as expected.

Here is the beta to test: [uBlock0_1.16.4.31b1.firefox-legacy.xpi.zip](https://github.com/gorhill/uBlock-for-firefox-legacy/files/7583908/uBlock0_1.16.4.31b1.firefox-legacy.xpi.zip) (rename zip to xpi).

Ping @smnthermes, @quisquose, @THEtomaso.

**Comment by hawkeye116477** [comment]
Is @JustOff forgot about that or I need to fix something?

In case of that mentioned people, seems that they aren't interested in it.

**Comment by JustOff** [comment]
I did not forget about your pull request, it is completely fine and ready to merge. The point is that I was hoping to find the time to also update scriptlets and filter lists before releasing a new version, but I still could not cope with this task.

**Comment by THEtomaso** [comment]
> I was hoping to find the time to also update scriptlets

@JustOff:
Could that possibly fix this issue?:
https://github.com/uBlockOrigin/uAssets/issues/11422/

**Pull request merged**
