### PR TITLE
Add procedural cosmetic operators remove() and upward()

### LINKED ISSUE #224: Add support for ":nth-ancestor" and ":upward"
While I haven't tested it in Pale Moon (nor SeaMonkey) myself, I think uBO added the new ":nth-ancestor" feature to the regular uBO versions sometime in the past year, and I'm already liking it enough that I'm predicting it'll become a major feature in uBO-specific lists within the next year or two.

So I presume that adding support for it would be advantageous for you guys.

### LINKED ISSUE #232: v1.16.4.21?
Might just as well release it with the current changes, don't you think?

### LINKED ISSUE #233: Add support for ":remove()"
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It would be great if uBO Legacy will support procedural cosmetic operator `remove()`.
https://github.com/gorhill/uBlock/commit/72bb70056843024b1a31fe1ab9c90bd4e8260ba2.
Can you make my dream come true?

### PR DESCRIPTION
**Pull request by hawkeye116477**
Fixes #233 and fixes #224. Code is almost original, only changed const to let in for of loop.

### CODE REVIEW

**Comment by JustOff** [comment]
Thank you, but could you please update the commit to include the original description from https://github.com/gorhill/uBlock/commit/72bb70056843024b1a31fe1ab9c90bd4e8260ba2?

Please use `git commit --amend` + `git push -f` to update this PR and not create a new one.

**Comment by hawkeye116477** [comment]
@JustOff Done

**Comment by JustOff** [comment]
Thanks, I started using this in my main browser and if nothing unexpected happens I'm going to initiate a release early next week.

**Comment by JustOff** [comment]
It seems that [changes to cosmetic-logger.js](https://github.com/gorhill/uBlock-for-firefox-legacy/pull/252/files#diff-fe57879eb27e2bdc0b78a77743617201) are [not working as expected](https://github.com/gorhill/uBlock-for-firefox-legacy/issues/224#issuecomment-660172262). I guess we can just exclude them, right?

**Comment by hawkeye116477** [comment]
Ooops, seems that change was related with https://github.com/gorhill/uBlock/commit/3573b6b32c3f5721eb606b1e0698ed66497ab080#diff-fe57879eb27e2bdc0b78a77743617201. Anyway, should be fixed with latest commit.

**Comment by JustOff** [comment]
> Anyway, should be fixed with latest commit.

Yep, it seems it is.

**Pull request merged**
